import React from "react";
import style from "./SpringList.module.css";

const SpringList = () => {
  return (
    <>
      <div className={style.masterDiv}>
        <div className={style.mainDiv}>
          <img
            src="https://cdn.fcglcdn.com/brainbees/images/cattemplate/1920_236_desktop_spring_2023_05.jpg"
            alt="Sprint banner"
          />
        </div>
        <div className={style.imgCardDivs}>
          <div>
            <img
              src="https://cdn.fcglcdn.com/brainbees/images/cattemplate/fashion_desktop_spring_060223_06.jpg"
              alt=""
            />
          </div>
          <div>
            <img
              src="https://cdn.fcglcdn.com/brainbees/images/cattemplate/fashion_desktop_spring_060223_07.jpg"
              alt=""
            />
          </div>
          <div>
            <img
              src="https://cdn.fcglcdn.com/brainbees/images/cattemplate/fashion_desktop_spring_060223_08.jpg"
              alt=""
            />
          </div>
          <div>
            <img
              src="https://cdn.fcglcdn.com/brainbees/images/cattemplate/fashion_desktop_spring_060223_09.jpg"
              alt=""
            />
          </div>
          <div>
            <img
              src="https://cdn.fcglcdn.com/brainbees/images/cattemplate/fashion_desktop_spring_060223_10.jpg"
              alt=""
            />
          </div>
          <div>
            <img
              src="https://cdn.fcglcdn.com/brainbees/images/cattemplate/fashion_desktop_spring_060223_11.jpg"
              alt=""
            />
          </div>
          <div>
            <img
              src="https://cdn.fcglcdn.com/brainbees/images/cattemplate/fashion_desktop_spring_060223_12.jpg"
              alt=""
            />
          </div>
          <div>
            <img
              src="https://cdn.fcglcdn.com/brainbees/images/cattemplate/fashion_desktop_spring_060223_13.jpg"
              alt=""
            />
          </div>
        </div>
        {/* Infant's Corner */}
        <div className={style.mainDiv}>
          <img
            src="https://cdn.fcglcdn.com/brainbees/images/cattemplate/1920_196_desktop_spring_2023_14.jpg"
            alt="Sprint banner"
          />
        </div>
        <div className={style.imgCardDivs}>
          <div>
            <img
              src="https://cdn.fcglcdn.com/brainbees/images/cattemplate/fashion_desktop_spring_060223_15.jpg"
              alt=""
            />
          </div>
          <div>
            <img
              src="https://cdn.fcglcdn.com/brainbees/images/cattemplate/fashion_desktop_spring_060223_16.jpg"
              alt=""
            />
          </div>
          <div>
            <img
              src="https://cdn.fcglcdn.com/brainbees/images/cattemplate/fashion_desktop_spring_060223_17.jpg"
              alt=""
            />
          </div>
          <div>
            <img
              src="https://cdn.fcglcdn.com/brainbees/images/cattemplate/fashion_desktop_spring_060223_18.jpg"
              alt=""
            />
          </div>
          <div>
            <img
              src="https://cdn.fcglcdn.com/brainbees/images/cattemplate/fashion_desktop_spring_060223_19.jpg"
              alt=""
            />
          </div>
        </div>
        {/* Age Groups */}
        <div className={style.mainDiv}>
          <img
            src="https://cdn.fcglcdn.com/brainbees/images/cattemplate/1920_230_desktop_spring_2023_20.jpg"
            alt="Sprint banner"
          />
        </div>
        <div className={style.imgCardDivs}>
          <div>
            <img
              src="https://cdn.fcglcdn.com/brainbees/images/cattemplate/fashion_desktop_spring_060223_21.jpg"
              alt=""
            />
          </div>
          <div>
            <img
              src="https://cdn.fcglcdn.com/brainbees/images/cattemplate/fashion_desktop_spring_060223_22.jpg"
              alt=""
            />
          </div>
          <div>
            <img
              src="https://cdn.fcglcdn.com/brainbees/images/cattemplate/fashion_desktop_spring_060223_23.jpg"
              alt=""
            />
          </div>
          <div>
            <img
              src="https://cdn.fcglcdn.com/brainbees/images/cattemplate/fashion_desktop_spring_060223_24.jpg"
              alt=""
            />
          </div>
          <div>
            <img
              src="https://cdn.fcglcdn.com/brainbees/images/cattemplate/fashion_desktop_spring_060223_25.jpg"
              alt=""
            />
          </div>
          <div>
            <img
              src="https://cdn.fcglcdn.com/brainbees/images/cattemplate/fashion_desktop_spring_060223_26.jpg"
              alt=""
            />
          </div>
          <div>
            <img
              src="https://cdn.fcglcdn.com/brainbees/images/cattemplate/fashion_desktop_spring_060223_27.jpg"
              alt=""
            />
          </div>
          <div>
            <img
              src="https://cdn.fcglcdn.com/brainbees/images/cattemplate/fashion_desktop_spring_060223_28.jpg"
              alt=""
            />
          </div>
        </div>
        {/* Beloved Brands */}
        <div className={style.mainDiv}>
          <img
            src="https://cdn.fcglcdn.com/brainbees/images/cattemplate/1920_223_desktop_spring_2023_29.jpg"
            alt="Sprint banner"
          />
        </div>
        <div className={style.BelovedCardDivs}>
          <div>
            <img
              src="https://cdn.fcglcdn.com/brainbees/images/cattemplate/fashion_desktop_spring_01032022_19.jpg"
              alt=""
            />
          </div>
          <div>
            <img
              src="https://cdn.fcglcdn.com/brainbees/images/cattemplate/fashion_desktop_spring_01032022_20.jpg"
              alt=""
            />
          </div>
          <div>
            <img
              src="https://cdn.fcglcdn.com/brainbees/images/cattemplate/fashion_desktop_spring_01032022_21.jpg"
              alt=""
            />
          </div>
          <div>
            <img
              src="https://cdn.fcglcdn.com/brainbees/images/cattemplate/fashion_desktop_spring_01032022_22.jpg"
              alt=""
            />
          </div>
          <div>
            <img
              src="https://cdn.fcglcdn.com/brainbees/images/cattemplate/fashion_desktop_spring_01032022_23.jpg"
              alt=""
            />
          </div>
          <div>
            <img
              src="https://cdn.fcglcdn.com/brainbees/images/cattemplate/fashion_desktop_spring_1111101032022_24.jpg"
              alt=""
            />
          </div>
          <div>
            <img
              src="https://cdn.fcglcdn.com/brainbees/images/cattemplate/fashion_desktop_spring_01032022_25.jpg"
              alt=""
            />
          </div>
          <div>
            <img
              src="https://cdn.fcglcdn.com/brainbees/images/cattemplate/fashion_desktop_spring_01032022_26.jpg"
              alt=""
            />
          </div>
          <div>
            <img
              src="https://cdn.fcglcdn.com/brainbees/images/cattemplate/fashion_desktop_spring_01032022_27.jpg"
              alt=""
            />
          </div>
          <div>
            <img
              src="https://cdn.fcglcdn.com/brainbees/images/cattemplate/fashion_desktop_spring_01032022_28_doodle_poodle.jpg"
              alt=""
            />
          </div>
          <div>
            <img
              src="https://cdn.fcglcdn.com/brainbees/images/cattemplate/fashion_desktop_spring_0103202_ED_A_MAMA.jpg"
              alt=""
            />
          </div>
          <div>
            <img
              src="https://cdn.fcglcdn.com/brainbees/images/cattemplate/fashion_desktop_spring_01032022_30.jpg"
              alt=""
            />
          </div>
          <div>
            <img
              src="https://cdn.fcglcdn.com/brainbees/images/cattemplate/fashion_desktop_spring_01032022_31.jpg"
              alt=""
            />
          </div>
          <div>
            <img
              src="https://cdn.fcglcdn.com/brainbees/images/cattemplate/fashion_desktop_spring_01032022_32.jpg"
              alt=""
            />
          </div>
          <div>
            <img
              src="https://cdn.fcglcdn.com/brainbees/images/cattemplate/fashion_desktop_spring_01032022_33.jpg"
              alt=""
            />
          </div>
          <div>
            <img
              src="https://cdn.fcglcdn.com/brainbees/images/cattemplate/fashion_desktop_spring_01032022_34.jpg"
              alt=""
            />
          </div>
          <div>
            <img
              src="https://cdn.fcglcdn.com/brainbees/images/cattemplate/fashion_desktop_spring_01032022_35.jpg"
              alt=""
            />
          </div>
          <div>
            <img
              src="https://cdn.fcglcdn.com/brainbees/images/cattemplate/fashion_desktop_spring_01032022_36.jpg"
              alt=""
            />
          </div>
          <div>
            <img
              src="https://cdn.fcglcdn.com/brainbees/images/cattemplate/fashion_desktop_spring_01032022_37.jpg"
              alt=""
            />
          </div>
          <div>
            <img
              src="https://cdn.fcglcdn.com/brainbees/images/cattemplate/fashion_desktop_spring_01032022_38.jpg"
              alt=""
            />
          </div>
          <div>
            <img
              src="https://cdn.fcglcdn.com/brainbees/images/cattemplate/wingsfield_26_09_2022.jpg"
              alt=""
            />
          </div>
          <div>
            <img
              src="https://cdn.fcglcdn.com/brainbees/images/cattemplate/fashion_desktop_spring__1111101032022_40.jpg"
              alt=""
            />
          </div>
          <div>
            <img
              src="https://cdn.fcglcdn.com/brainbees/images/cattemplate/fashion_desktop_spring__1111101032022_41.jpg"
              alt=""
            />
          </div>
          <div>
            <img
              src="https://cdn.fcglcdn.com/brainbees/images/cattemplate/fashion_desktop_spring_01032022_42.jpg"
              alt=""
            />
          </div>
          <div>
            <img
              src="https://cdn.fcglcdn.com/brainbees/images/cattemplate/fashion_desktop_spring_12052022_43.jpg"
              alt=""
            />
          </div>
          <div>
            <img
              src="https://cdn.fcglcdn.com/brainbees/images/cattemplate/fashion_desktop_spring_12052022_44.jpg"
              alt=""
            />
          </div>
          <div>
            <img
              src="https://cdn.fcglcdn.com/brainbees/images/cattemplate/fashion_new_desktop_spring_12052022_45.jpg"
              alt=""
            />
          </div>
          <div>
            <img
              src="https://cdn.fcglcdn.com/brainbees/images/cattemplate/fashion_desktop_spring_12052022_46_EARTHY_TOUCH.jpg"
              alt=""
            />
          </div>
          <div>
            <img
              src="https://cdn.fcglcdn.com/brainbees/images/cattemplate/fashion_desktop_spring_skechesr_12052022_47.jpg"
              alt=""
            />
          </div>
          <div>
            <img
              src="https://cdn.fcglcdn.com/brainbees/images/cattemplate/fashion_desktop_spring__1111112052022_48.jpg"
              alt=""
            />
          </div>
          <div>
            <img
              src="https://cdn.fcglcdn.com/brainbees/images/cattemplate/fashion_desktop_spring_new_12052022_49.jpg"
              alt=""
            />
          </div>
          <div>
            <img
              src="https://cdn.fcglcdn.com/brainbees/images/cattemplate/fashion_desktop_spring_12052022_50.jpg"
              alt=""
            />
          </div>
        </div>
        {/* Elegant Ensembles */}
        <div className={style.mainDiv}>
          <img
            src="https://cdn.fcglcdn.com/brainbees/images/cattemplate/1920_207_desktop_spring_2023_30.jpg"
            alt="Elegant Ensembles  "
          />
        </div>
        <div className={style.imgCardDivs}>
          <div>
            <img
              src="https://cdn.fcglcdn.com/brainbees/images/cattemplate/fashion_desktop_spring_060223_31.jpg"
              alt=""
            />
          </div>
          <div>
            <img
              src="https://cdn.fcglcdn.com/brainbees/images/cattemplate/fashion_desktop_spring_060223_32.jpg"
              alt=""
            />
          </div>
        </div>
        {/* Just In Accessories */}
        <div className={style.mainDiv}>
          <img src="https://cdn.fcglcdn.com/brainbees/images/cattemplate/1920_153_desktop_spring_2023_33.jpg" />
        </div>
        <div className={style.imgCardDivs}>
          <div>
            <img
              src="https://cdn.fcglcdn.com/brainbees/images/cattemplate/fashion_desktop_spring_060223_34.jpg"
              alt=""
            />
          </div>
          <div>
            <img
              src="https://cdn.fcglcdn.com/brainbees/images/cattemplate/fashion_desktop_spring_060223_35.jpg"
              alt=""
            />
          </div>
          <div>
            <img
              src="https://cdn.fcglcdn.com/brainbees/images/cattemplate/fashion_desktop_spring_060223_36.jpg"
              alt=""
            />
          </div>
          <div>
            <img
              src="https://cdn.fcglcdn.com/brainbees/images/cattemplate/fashion_desktop_spring_060223_37.jpg"
              alt=""
            />
          </div>
          <div>
            <img
              src="https://cdn.fcglcdn.com/brainbees/images/cattemplate/fashion_desktop_spring_060223_38.jpg"
              alt=""
            />
          </div>
          <div>
            <img
              src="https://cdn.fcglcdn.com/brainbees/images/cattemplate/fashion_desktop_spring_060223_39.jpg"
              alt=""
            />
          </div>
          <div>
            <img
              src="https://cdn.fcglcdn.com/brainbees/images/cattemplate/fashion_desktop_spring_060223_39.jpg"
              alt=""
            />
          </div>
          <div>
            <img
              src="https://cdn.fcglcdn.com/brainbees/images/cattemplate/fashion_desktop_spring_060223_40.jpg"
              alt=""
            />
          </div>
          <div>
            <img
              src="https://cdn.fcglcdn.com/brainbees/images/cattemplate/fashion_desktop_spring_060223_41.jpg"
              alt=""
            />
          </div>
        </div>
        {/* Daily Care Essentials */}
        <div className={style.mainDiv}>
          <img src="https://cdn.fcglcdn.com/brainbees/images/cattemplate/spring_desktop_essentials_100223_01.jpg" />
        </div>
        <div className={style.imgCardDivs}>
          <div>
            <img
              src="https://cdn.fcglcdn.com/brainbees/images/cattemplate/mmspring_desktop_moms-_&_maternity_100223_03.jpg"
              alt=""
            />
          </div>
          <div>
            <img
              src="https://cdn.fcglcdn.com/brainbees/images/cattemplate/mmspring_desktop_moms-_&_maternity_100223_04.jpg"
              alt=""
            />
          </div>
          <div>
            <img
              src="https://cdn.fcglcdn.com/brainbees/images/cattemplate/mmspring_desktop_moms-_&_maternity_100223_05.jpg"
              alt=""
            />
          </div>
          <div>
            <img
              src="https://cdn.fcglcdn.com/brainbees/images/cattemplate/mmspring_desktop_moms-_&_maternity_100223_06.jpg"
              alt=""
            />
          </div>
          <div>
            <img
              src="https://cdn.fcglcdn.com/brainbees/images/cattemplate/mmspring_desktop_moms-_&_maternity_100223_07.jpg"
              alt=""
            />
          </div>
          <div>
            <img
              src="https://cdn.fcglcdn.com/brainbees/images/cattemplate/mmspring_desktop_moms-_&_maternity_100223_08.jpg"
              alt=""
            />
          </div>
        </div>
        <div className={style.imgCardDivs}>
          <div>
            <img
              src="https://cdn.fcglcdn.com/brainbees/images/cattemplate/mmspring_desktop_moms-_&_maternity_100223_11.jpg"
              alt=""
            />
          </div>
          <div>
            <img
              src="https://cdn.fcglcdn.com/brainbees/images/cattemplate/mmspring_desktop_moms-_&_maternity_100223_12.jpg"
              alt=""
            />
          </div>
          <div>
            <img
              src="https://cdn.fcglcdn.com/brainbees/images/cattemplate/mmspring_desktop_moms-_&_maternity_100223_13.jpg"
              alt=""
            />
          </div>
          <div>
            <img
              src="https://cdn.fcglcdn.com/brainbees/images/cattemplate/mmspring_desktop_moms-_&_maternity_100223_14.jpg"
              alt=""
            />
          </div>

          <div>
            <img
              src="https://cdn.fcglcdn.com/brainbees/images/cattemplate/mmspring_desktop_moms-_&_maternity_100223_15.jpg"
              alt=""
            />
          </div>
          <div>
            <img
              src="https://cdn.fcglcdn.com/brainbees/images/cattemplate/mmspring_desktop_moms-_&_maternity_100223_16.jpg"
              alt=""
            />
          </div>
        </div>
        {/* contest alert */}
        <div className={style.mainDiv}>
          <img
            style={{ height: "300px" }}
            src="https://cdn.fcglcdn.com/brainbees/images/intellitots-franchise-1dec22.webp"
          />
        </div>
      </div>
    </>
  );
};

export default SpringList;
